# Generated by Django 5.2.7 on 2025-10-25 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'ANALYSTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='Créé par (Analyste)')),
            ],
            options={
                'verbose_name': 'Questionnaire (Template)',
                'verbose_name_plural': 'Questionnaires (Templates)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texte de la question')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.questionnaire', verbose_name='Questionnaire')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='questionnaire_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])], verbose_name='Fichier')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='questionnaires.questionnaire', verbose_name='Questionnaire')),
            ],
            options={
                'verbose_name': 'Document du questionnaire',
                'verbose_name_plural': 'Documents des questionnaires',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_ATTENTE', 'En attente'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaires.questionnaire', verbose_name='Questionnaire (Template)')),
                ('responder', models.ForeignKey(limit_choices_to={'role': 'CHEF_PROJET'}, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL, verbose_name='Rempli par (Chef de projet)')),
            ],
            options={
                'verbose_name': 'Réponse au questionnaire',
                'verbose_name_plural': 'Réponses aux questionnaires',
                'ordering': ['-created_at'],
                'unique_together': {('questionnaire', 'responder')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questionnaires.questionnaireresponse', verbose_name='Réponse au questionnaire')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='response_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name="Fichier d'architecture")),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='questionnaires.questionnaireresponse', verbose_name='Réponse au questionnaire')),
            ],
            options={
                'verbose_name': 'Document de réponse',
                'verbose_name_plural': 'Documents de réponse',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_ATTENTE', 'En attente'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], max_length=20, null=True, verbose_name='Ancien statut')),
                ('new_status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_ATTENTE', 'En attente'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], max_length=20, verbose_name='Nouveau statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='questionnaires.questionnaireresponse', verbose_name='Réponse au questionnaire')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.question', verbose_name='Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.questionnaireresponse', verbose_name='Réponse au questionnaire')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
