# Generated by Django 5.2.7 on 2025-11-02 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coherence_score', models.IntegerField(help_text='Score de 0 à 100 indiquant la cohérence entre réponses et documents', verbose_name='Score de cohérence global')),
                ('confidentiality_score', models.IntegerField(help_text='Score CIA - Confidentialité', verbose_name='Score de confidentialité')),
                ('integrity_score', models.IntegerField(help_text='Score CIA - Intégrité', verbose_name="Score d'intégrité")),
                ('availability_score', models.IntegerField(help_text='Score CIA - Disponibilité', verbose_name='Score de disponibilité')),
                ('analysis_summary', models.TextField(help_text="Résumé général de l'analyse IA", verbose_name="Résumé de l'analyse")),
                ('inconsistencies', models.JSONField(blank=True, default=list, help_text='Liste des incohérences entre réponses et documents', verbose_name='Incohérences détectées')),
                ('strengths', models.JSONField(blank=True, default=list, help_text="Points positifs identifiés par l'IA", verbose_name='Points forts')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text="Points d'amélioration identifiés par l'IA", verbose_name='Points faibles')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text="Recommandations de sécurité de l'IA", verbose_name='Recommandations')),
                ('question_analysis', models.JSONField(blank=True, default=dict, help_text='Analyse détaillée question par question', verbose_name='Analyse par question')),
                ('model_used', models.CharField(help_text='Ex: gpt-4o-mini', max_length=100, verbose_name='Modèle IA utilisé')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Temps de traitement (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('analyst', models.ForeignKey(limit_choices_to={'role': 'ANALYSTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses_requested', to=settings.AUTH_USER_MODEL, verbose_name='Analyste demandeur')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='questionnaires.questionnaireresponse', verbose_name='Réponse au questionnaire')),
            ],
            options={
                'verbose_name': 'Analyse IA',
                'verbose_name_plural': 'Analyses IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
