# Generated by Django 5.2.7 on 2025-11-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_aianalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', help_text="Langue dans laquelle l'analyse a été générée (fr ou en)", max_length=10, verbose_name="Langue de l'analyse"),
        ),
    ]
